config/routes.rb
ReviewSite::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  
  get '/locations/searchyelp_byid', to: 'locations#searchyelp_byid'
  get '/locations/searchyelp', to: 'locations#searchyelp'
  
  post '/locations/detail', to: 'locations#detail'
  post '/locations/add_review', to: 'locations#add_review'
  
  post "/locations/searchresult"
  
  resources :locations do
#  	match '/location/new' => 'locations#new'
#  	match '/locations' => 'locations#new'
  end

  resources :rating
  match '/rating/:id/edit' => 'rating#update'
  match '/rating/new' => 'rating#create'
  #match '/rating', to: 'rating#index', via: :post
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	

  end
  
  def show
  	puts "home cntrl show"
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>

<script type="text/javascript">	
<!--
function ValidateForm(){

	var form = document.forms['searchform'];
	if ((form['location_search'].value == "") || !(form['location_search'].value)){
		 alert("You did not provide a search term!");
		 return(false);
	} else {
		return(true);
	}
	
}
-->
</script>

<div class="hero">
<div class="hero-inner">
<h1>Rate and review Places</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui, veritatis, neque, adipisci assumenda doloribus quaerat minima optio suscipit nihil earum quidem sint tempora culpa pariatur delectus cupiditate voluptate aspernatur dignissimos.</p>
<div class="search-bar">
  <div class="search-item">
	  <div class="search-and-submit control-group">
			  <%= form_for :location, :html => {:id => "searchform", :onsubmit => "return ValidateForm();" }, :url => locations_searchresult_path() do |f| %>
			  <%= hidden_field_tag("hidden_googleid", "", {:class => "hidden_googleid"}) %>
		    <%= hidden_field_tag("hidden_googlereference", "", {:class => "hidden_googlereference"}) %>
		    <%= text_field_tag :location_search, nil, class: "span12 search-query", type: "search", placeholder: "Search for establishment, hotel, restaurant, city, etc", :onkeyup => 'if (event.keyCode == 13) {document.forms["searchform"].submit()}' %>
		    <div class="clear-search">
		    <a href="" onclick="return clearSearch();">&#10799;</a>
        <input id="searchbutton" type="submit" value="Search">
    </div>
    </div>
 			<% end %>
    </div>
  </div>
</div>
<br>
<center><a href="/locations">All stored locations</a></center>
</div>
</div>


<script type="text/javascript">	
<!--

// Address Autocomplete
var input = document.getElementById('location_search');
var autocomplete = new google.maps.places.Autocomplete(input);
	
// Autocomplete Listener
google.maps.event.addListener(autocomplete, 'place_changed', function() {
              
	place = autocomplete.getPlace();
	
	var a = [];
	a = document.getElementsByClassName("hidden_googleid");
	for(i = 0;i < a.length; ++i) {
      a[i].value = place.id;      
  }
	a = document.getElementsByClassName("hidden_googlereference");
	for(i = 0;i < a.length; ++i) {
      a[i].value = place.reference;      
  }

	document.forms['searchform'].submit();
		
}); 	


function clearSearch() {
	document.getElementById('location_search') = '';
	return false;
}

-->
</script>