config/routes.rb
ReviewSite::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  
  get '/locations/searchyelp_byid', to: 'locations#searchyelp_byid'
  get '/locations/searchyelp', to: 'locations#searchyelp'
  
  post '/locations/detail', to: 'locations#detail'
  post '/locations/add_review', to: 'locations#add_review'
  
  post "/locations/searchresult"
  
  resources :locations do
#  	match '/location/new' => 'locations#new'
#  	match '/locations' => 'locations#new'
  end

  resources :rating
  match '/rating/:id/edit' => 'rating#update'
  match '/rating/new' => 'rating#create'
  #match '/rating', to: 'rating#index', via: :post
  
end

app/models/location.rb
class Location
	include Mongoid::Document
	include Mongoid::Timestamps

	## Database authenticatable
	field :id, :type => Integer, :default => ""
	field :address, :type => String, :default => ""
	field :location_name, :type => String, :default => ""
	field :phone_number, :type => String, :default => ""
	field :district, :type => String, :default => ""
	field :postcode, :type => String, :default => ""
	field :city, :type => String, :default => ""
	field :country, :type => String, :default => ""
	field :lat, :type => Float, :default => ""
	field :lng, :type => Float, :default => ""
	field :created_at, :type => Time, :default => ""
	field :updated_at, :type => Time, :default => ""
	field :googleid, :type => String, :default => ""
	field :googlereference, :type => String, :default => ""
	field :yelpbusinessid, :type => String, :default => ""
	
   
	validates_presence_of :address
	validates_presence_of :location_name



	attr_accessible :address
	attr_accessible :location_name
	attr_accessible :phone_number
	attr_accessible :district
	attr_accessible :postcode
	attr_accessible :city
	attr_accessible :country
	attr_accessible :lat
	attr_accessible :lng
	attr_accessible :googleid
	attr_accessible :googlereference
	attr_accessible :yelpbusinessid
 
	has_many :ratings
	#has_many :raters, :through => :ratings, :source => :user
	
	def raters
    User.in(id: ratings.map(&:user_id))
  end
  
	def average_cat1_rating
		@value = 0
		self.ratings.each do |rating|
			if !rating.Cat1value.nil?
				@value = @value + rating.Cat1value
			end
		end
		@total = self.ratings.size
		if !@total.nil?
			@value = @value.to_f / @total.to_f
			#puts @value
			@value = 0.0 unless @value.finite?
		end
		return @value
	end

	def average_cat2_rating
		@value = 0
		self.ratings.each do |rating|
			if !rating.Cat2value.nil?
				@value = @value + rating.Cat2value
			end
		end
		@total = self.ratings.size
		if !@total.nil?
			@value = @value.to_f / @total.to_f
			#puts @value
			@value = 0.0 unless @value.finite?
		end
		return @value
	end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

			
	# GET /locations
  # GET /locations.json
  def index
    #@locations = Location.order("id desc").page(params[:page]).per(50)
    @locations = Location.all
    
    puts "loc controller index"
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show

	  @location = Location.find(params[:id])
	
	  respond_to do |format|
	    format.html # show.html.erb
	    format.json { render json: @location }
	  end

  end

  # GET /locations/new
  # GET /locations/new.json
  def new
  
  	puts "loc controller new"
  
#	  @stored_locations = Location.all.each
	  #@stored_locations = Array.new

	  
		# construct a yelp client instance
#		client = Yelp::Client.new
		
		# perform an address/location-based search for cream puffs nearby
#		request = Yelp::V1::Review::Request::Location.new(
#					     :address => '650 Mission St',
#					     :city => 'San Francisco',
#					     :state => 'CA',
#					     :radius => 2,
#					     :term => 'cream puffs',
#					     :yws_id => 'H7JaEQfqf4qG-AvyBRIbgQ')
#		
#		response = client.search(request)
#		puts "yelp response"
#		businesses = response["businesses"]
#		
#		businesses.each do |singlebusiness|
#			puts singlebusiness["name"]	
#		end		
             
             
		# Make request to retrieve details of business vi yelp business id 
#		request = Yelp::V2::Business::Request::Id.new(
#				:yelp_business_id => "pjb2WMwa0AfK3L-dWimO8w",
#				:consumer_key     => 'bfGBEV3Ej3EQqo2vGta9ow',
#				:consumer_secret  => 'imgLOjWNHYERDU0D2FCJkMTlhf4',
#				:token            => 'vgAIJOqBJbzIY_9H5pTsheSP93xgUQzj',
#				:token_secret     => 'vDGFGE9pYzyGPdTVD8f1VYkg26Q')

#		singlebusiness = client.search(request)
#		puts "yelp response"
#		puts singlebusiness["name"]



 # search for businesses via bounding box geo coords'
# request = Yelp::V2::Search::Request::BoundingBox.new(
#						:term => "cream puffs",
#						:sw_latitude => 37.900000,
#						:sw_longitude => -122.500000,
#						:ne_latitude => 37.788022,
#						:ne_longitude => -122.399797,
#						:limit => 3,
#						:consumer_key     => 'bfGBEV3Ej3EQqo2vGta9ow',
#						:consumer_secret  => 'imgLOjWNHYERDU0D2FCJkMTlhf4',
#						:token            => 'vgAIJOqBJbzIY_9H5pTsheSP93xgUQzj',
#						:token_secret     => 'vDGFGE9pYzyGPdTVD8f1VYkg26Q')
# @yelpresponse = client.search(request)

# # perform an address/location-based search for cream puffs nearby
# request = Yelp::V1::Review::Request::Location.new(
#             :address => '650 Mission St',
#             :city => 'San Francisco',
#             :state => 'CA',
#             :radius => 2,
#             :term => 'cream puffs',
#             :yws_id => 'H7JaEQfqf4qG-AvyBRIbgQ')
# response = client.search(request)

	
	
	
		
#		response.each do |resp|
#			if resp.kind_of?(Array)
#				if resp[0] == "name"
#					puts resp[1]
#				end
#			end
#		end

		
#		if response.is_a?(Hash)
#			if response.has_key?("name")
#				puts singlebusiness["name"]	
#			end
#		end
		
#		keys = response.keys
#		puts "#{keys}"
		
#		response["businesses"].each { |x| puts x }
		

#		puts params['location_search']



    @location = Location.new

    respond_to do |format|
      #format.html # new.html.erb
      #format.html { redirect_to :controller=>'home', :action => 'index', :id => @location.id}
      format.html { redirect_to :controller=>'home', :action => 'index', :id => @location.id}
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
  	puts "loc controller create"
  	
  	loc = Location.where(:googleid => params[:hidden_googleid])
  	
		if loc.any?
			puts "found record in db"
			@location = loc.first
		else
  	
    	@location = Location.new(params[:location])
    
    	@location.yelpbusinessid = params[:yelpbusinessid]
    	@location.googleid = params[:googleid]
    	@location.googlereference = params[:googlereference]
    end
    
    if current_user.present?
    	@rating = Rating.new(:user_id => current_user.id, :location_id => @location.id, :Cat1value => params[:starCat1], :Cat1comment => params[:Cat1Comment], :Cat2value => params[:starCat2], :Cat2comment => params[:Cat2Comment])
    else
    	string = "anon"
		  length=6
			chars = ("A".."Z").to_a
			length.times do
		  	string << chars[rand(chars.length-1)]
			end
			
    	@rating = Rating.new(:user_id => string, :location_id => @location.id, :Cat1value => params[:starCat1], :Cat1comment => params[:Cat1Comment], :Cat2value => params[:starCat2], :Cat2comment => params[:Cat2Comment])
    end
    
    respond_to do |format|
      if @location.save
      	if @rating.save
		      format.html { redirect_to @location, notice: 'Location was successfully created.' }
		      format.json { render json: @location, status: :created, location: @location }      	
      	else
		      format.html { render action: "new" }
		      format.json { render json: @rating.errors, status: :unprocessable_entity }      	
      	end
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
  	puts "loc controller update"
  	
    @location = Location.find(params[:id])
    
    
    if current_user.present?
    
    	rat = Rating.where({:user_id => current_user.id, :location_id => @location.id})
  	
			if rat.any?
				puts "found rating in db"
				@rating = rat.first
				
				if @rating.update_attributes(params[:location])
					puts "rating updated"
				else
					puts "could not update rating"
				end
				
			else
    		@rating = Rating.new(:user_id => current_user.id, :location_id => @location.id, :Cat1value => params[:starCat1], :Cat1comment => params[:Cat1Comment], :Cat2value => params[:starCat2], :Cat2comment => params[:Cat2Comment])
    	
		  	if @rating.save
		  		puts "rating saved"
		  	else
		  		puts "couldn't save rating"
		  	end
		  end
    	
    else
    
		  string = "anon"
		  length=6
			chars = ("A".."Z").to_a
			length.times do
		  	string << chars[rand(chars.length-1)]
			end
	    @rating = Rating.new(:user_id => string, :location_id => @location.id, :Cat1value => params[:starCat1], :Cat1comment => params[:Cat1Comment], :Cat2value => params[:starCat2], :Cat2comment => params[:Cat2Comment])
	    
     	if @rating.save
	  		puts "rating saved"
	  	else
	  		puts "couldn't save rating"
	  	end
	    
    end

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy

#####################  	
# should only be used as cleanup / administrative
#####################  	
  	
  	location = Location.find(params[:id])
  	
  	if !location.nil?
	  	#puts location.location_name
			location.ratings.each do |rating|
				rating.destroy
				#puts rating.Cat1value
			end
		  location.destroy
    end
  	
  	respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully deleted.' }
      format.json { head :no_content }
    end

  end
  
  def detail
  	puts "loc controller detail"
  	
  	loc = Location.where(:googleid => params[:hidden_googleid])
  	
		if loc.any?
			puts "found record in db"
			@location = loc.first
		else
			puts "new location"  	
			@location = Location.new(:googleid => params[:hidden_googleid], :googlereference => params[:hidden_googlereference], :yelpbusinessid => params[:hidden_yelpbusinessid2])
		end
	
  	respond_to do |format|
      format.html { render :template => "locations/detail" }
      format.json { render json: @location }
    end
  end
  
  def add_review
  	puts "loc controller add_review"
  	
  	@searchterm = params[:searchterm]

		if !params[:hidden_googleid].nil?
	  	loc = Location.where(:googleid => params[:hidden_googleid])

			if loc.any?
				puts "found record in db"
				@location = loc.first
			else
				puts "new location"  	
				@location = Location.new(:googleid => params[:hidden_googleid], :googlereference => params[:hidden_googlereference], :yelpbusinessid => params[:hidden_yelpbusinessid1])
			end
	  else
	  	@location = Location.new(:googleid => "", :googlereference => "", :yelpbusinessid => "")
		end
		 	
  	
  	respond_to do |format|
      format.html { render :template => "locations/addreview", :locals => {:location => @location}}
      format.json { render json: @location }
    end
  end
  
	def searchyelp
		puts "loc cntrl search yelp"
	
		@yelpresponse = String.new()
		@yelpbusinessid = String.new()
		
		client = Yelp::Client.new

		request = Yelp::V2::Search::Request::Location.new(
					     :address => params[:adr],
					     :city => params[:city],
					     :state => params[:state],
					     :radius => 1,
					     :term => params[:term],
					     :limit => 1,
					     :consumer_key     => 'bfGBEV3Ej3EQqo2vGta9ow',
					     :consumer_secret  => 'imgLOjWNHYERDU0D2FCJkMTlhf4',
					     :token            => 'vgAIJOqBJbzIY_9H5pTsheSP93xgUQzj',
					     :token_secret     => 'vDGFGE9pYzyGPdTVD8f1VYkg26Q')	

		response = client.search(request)
 		
 		businesses = response["businesses"]


		
		businesses.each do |singlebusiness|
			#keys = singlebusiness.keys
			#puts "#{keys}"
			
			#puts singlebusiness["name"]
			#puts singlebusiness["id"]
			#puts singlebusiness["location"]
			
			adr1 = params[:adr].sub(/Street/, 'St')
			adr2 = params[:adr].sub(/ St/, ' Street')
			

app/views/locations/_form.html.erb
<%= form_for(@location, html: { class: "form-horizontal" }) do |f| %>

<fieldset>
  <div class="row-fluid">

    <div class="span5">

      <div class="control-group">
        <%= f.label :address, "Address", class: "control-label" %>
        <div class="controls">
          <%= f.text_field :address, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :location_name, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :location_name, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :phone_number, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :phone_number, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :district, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :district, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :postcode, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :postcode, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :city, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :city, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :country, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :country, class: "span12" %>
        </div>
      </div>
      
      <div class="control-group">
      	Category 1
		    <div class="controls">
					<input name="starCat1" type="radio" class="star {split:2}" value="1"/>
					<input name="starCat1" type="radio" class="star {split:2}" value="2"/>
					<input name="starCat1" type="radio" class="star {split:2}" value="3"/>
					<input name="starCat1" type="radio" class="star {split:2}" value="4"/>
					<input name="starCat1" type="radio" class="star {split:2}" value="5"/>
					<br>
					<textarea cols="30" rows="3" name="Cat1Comment"></textarea>
        </div>
			</div>
			
      <div class="control-group">
      	Category 2
		    <div class="controls">
					<input name="starCat2" type="radio" class="star {split:2}" value="1"/>
					<input name="starCat2" type="radio" class="star {split:2}" value="2"/>
					<input name="starCat2" type="radio" class="star {split:2}" value="3"/>
					<input name="starCat2" type="radio" class="star {split:2}" value="4"/>
					<input name="starCat2" type="radio" class="star {split:2}" value="5"/>
					<br>
					<textarea cols="30" rows="3" name="Cat2Comment"></textarea>
				</div>
			</div>
			
      <div class="control-group">
        <%= f.label :lat, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :lat, class: "span12" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :lng, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :lng, class: "span12" %>
        </div>
      </div>
      <div class="control-group pull-right">
        <%= f.submit "Save Location", class: 'btn' %>
      </div>
    </div>

    <div class="span7">
      <% if @location.errors.any? %>
        <div class="notice">
          <h3>Errors</h2>
          <ul>
          <% @location.errors.full_messages.each do |msg| %>
            <li class="error"><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="control-group">
        <%= label_tag :search, "Search For Address" %>
        <%= text_field_tag :location_search, nil, class: "span12 search-query", type: "search" %>
      </div>
      <%= render partial: "googlemap" %>
    </div>
  </div>
</fieldset>
<% end %>

<div class="row-fluid">
  <div class="well span12">
    <h4>Images</h4>
    <div id="place_images"></div>
  </div>
</div>

app/views/locations/_googlemap_show.html.erb
<div id="map" style="width: 70%; height: 360px"></div>

<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>

<script type="text/javascript">
<!--
  var defaultZoom = 17; // Why zoomed in? Because it looks good.

  var lat = <%= @location.lat %>;
  var lng = <%= @location.lng %>;

  // create map and add controls
  var mapOptions = {
    center: new google.maps.LatLng(lat, lng),
    zoom: defaultZoom,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    scrollwheel: false,
    scaleControl: false
  };
  var map = new google.maps.Map(document.getElementById('map'),mapOptions);

  var mylat = document.getElementById("location_lat").value;
  var mylng = document.getElementById("location_lng").value;
  if (jQuery.isEmptyObject(mylat)) {
    var mylat = lat;
    var mylng = lng;
  };

  var centrePoint = new google.maps.LatLng(mylat, mylng);

  map.setCenter(centrePoint);
  map.setZoom(defaultZoom);

  marker = new google.maps.Marker({
    map:map,
    draggable: false,
    animation: google.maps.Animation.DROP,
    position: centrePoint
  });

  // Set marker image
  var defaultImage = new google.maps.MarkerImage(
      "http://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
      new google.maps.Size(71, 71),
      new google.maps.Point(0, 0),
      new google.maps.Point(17, 34),
      new google.maps.Size(35, 35)
  );
  marker.setIcon(defaultImage);

//-->
</script>

<br />

app/views/locations/detail.html.erb
<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>

<p><div id="googlemap" style="margin:auto; width:60%; height: 360px"></div></p>

<style type="text/css">
	/** FIX for Bootstrap and Google Maps Info window styes problem **/
	img[src*="gstatic.com/"], img[src*="googleapis.com/"] {
	max-width: none;
}
</style>

<script type="text/javascript">	
<!--

var defaultZoom = 16;

// create map and add controls
var mapOptions = {
	zoom: defaultZoom,
	mapTypeId: google.maps.MapTypeId.ROADMAP,
	scrollwheel: false,
	scaleControl: false
};

var infowindow = new google.maps.InfoWindow();

document.getElementById('googlemap').style.display = 'none';

var map = new google.maps.Map(document.getElementById('googlemap'),mapOptions);

function initialize() {

	var request = {
    reference: '<%=escape_javascript @location.googlereference %>'
	};

  var service = new google.maps.places.PlacesService(map);

	service.getDetails(request, function(place, status) {
    if (status == google.maps.places.PlacesServiceStatus.OK) {
    	
    	var marker = new google.maps.Marker({
        map: map,
				draggable: false,
        position: place.geometry.location
      });
      
      marker.setIcon(/** @type {google.maps.Icon} */({
				url: place.icon,
				size: new google.maps.Size(71, 71),
				origin: new google.maps.Point(0, 0),
				anchor: new google.maps.Point(17, 34),
				scaledSize: new google.maps.Size(35, 35)
			}));
      
			document.getElementById('googlemap').style.display = 'block';
			google.maps.event.trigger(map, "resize");
			map.setCenter(place.geometry.location);
      
      google.maps.event.addListener(marker, 'click', function() {
        infowindow.setContent(place.name);
        infowindow.open(map, this);
      });
      
      document.getElementById("address").innerHTML = place.formatted_address;
			document.getElementById("name").innerHTML = place.name;
			document.getElementById("googlerating").innerHTML = place.rating;
			
			//check yelp rating
			var yelpid = '<%=escape_javascript @location.yelpbusinessid %>';
			if (yelpid && yelpid.length != 0 && yelpid != null && yelpid != 'undefined') {
				document.getElementById("yelphref").href = "/locations/searchyelp_byid?yelpid=" + yelpid;
				document.getElementById("yelphref").click();			
			}	else {
				document.getElementById("yelphref").href = "/locations/searchyelp?term=" + place.name + "&state=" + place.address_components[3].short_name + "&city=" + place.address_components[2].short_name + "&adr=" + place.address_components[0].long_name + ' ' + place.address_components[1].short_name;
				document.getElementById("yelphref").click();
			}
			
    }
  });


  
}

google.maps.event.addDomListener(window, 'load', initialize);

-->
</script>

<a id="yelphref" href="" data-remote="true"></a>
 
<h1>Detail</h1>
<%= form_tag({:action => 'add_review', :controller => 'locations'}, {:id => "detail_form"}) do |f| %>
	<%= submit_tag("Add Review") %>
	
	<%= hidden_field_tag(:hidden_yelpbusinessid1, @location.yelpbusinessid) %>
	<%= hidden_field_tag(:hidden_googleid, @location.googleid) %>
	<%= hidden_field_tag(:hidden_googlereference, @location.googlereference) %>
	
	<br>
	<b>@location.location_name:</b><%= @location.location_name %>
	<!--
	<br>
	<b>googleid:</b><%= @location.googleid %>
	<br>
	<b>yelpid:</b><%= @location.yelpbusinessid %>
	-->
	
	<br>
	<b>Name:</b><p class="name" id="name"></p>
	<b>Address:</b><p class="address" id="address"></p>
	<b>Google rating:</b><p class="googlerating" id="googlerating"></p>
	<b>Yelp rating:</b><p class="yelprating" id="yelprating"></p>
	
  <p>
    <b>Avg Cat1 rating:</b>
    <%= @location.average_cat1_rating %>
  </p>

  <p>
    <b>Avg Cat2 rating:</b>
    <%= @location.average_cat2_rating %>
  </p>

<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="span11">
  <h3>Listing locations</h3>

  <table>
    <tr>
      <th>Location name</th>
      <th>Address</th>
      <th>City</th>
      <th>Country</th>
      <th>Date</th>
    </tr>

  <% @locations.each do |location| %>
    <tr>
      <td><%= link_to location.location_name, location %></td>
      <td><%= location.address %></td>
      <td><%= location.city %></td>
      <td><%= location.country %></td>
      <td><%= location.created_at.to_s(:short) %></td>
      <td><%= link_to "Delete", location_path(location), method: :delete, data: { confirm: 'Sure you want to delete location? Will also delete related ratings.' } if admin? %></td>
    </tr>
  <% end %>
  </table>


</div>

app/views/locations/new.html.erb
<%= render 'form' %>

app/views/locations/searchyelp.js.erb
$("#yelprating").html("<%= @yelpresponse %>");
$("#hidden_yelpbusinessid1").val("<%= @yelpbusinessid %>");
$("#hidden_yelpbusinessid2").val("<%= @yelpbusinessid %>");

app/views/locations/searchyelp_byid.js.erb
$("#yelprating").html("<%= @yelpresponse %>");

app/views/locations/show.html.erb
<div class="span11">
	<!--
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
	-->
	<h1>Show</h1>
	
  <p>
    <b>Address:</b>
    <%= @location.address %>
  </p>

  <p>
    <b>Location name:</b>
    <%= @location.location_name %>
  </p>

  <p>
    <b>City:</b>
    <%= @location.city %>
  </p>

  <p>
    <b>Country:</b>
    <%= @location.country %>
  </p>

  <p>
    <% if current_user.present? %>
    	<!-- user logged in -->
				<% if !Rating.where(:user_id => current_user.id, :location_id => @location.id).blank? %>
		  		<!-- user has rated this location earlier -->
		  		<% @rating = current_user.ratings.where(location_id: @location.id).first %>
		  		<% @rating.Cat1comment %>
				 	<%= form_for :rating, :url => edit_rating_path(:id => @rating.id) do |f| %>
				    <b>Your Cat1 rating:</b><br>
						<% (1..5).each do |i| %>
							<% if i == current_user_cat1_rating %>
								<input name="starCat1" type="radio" class="star" checked="checked" value="<%= i %>"/>
							<% else %>
								<input name="starCat1" type="radio" class="star" value="<%= i %>"/>
							<% end %>
						<% end %>
						<br>
						<textarea cols="30" rows="3" name="Cat1Comment"><%= @rating.Cat1comment %></textarea>
						<br>
				    <b>Your Cat2 rating:</b><br>
						<% (1..5).each do |i| %>
							<% if i == current_user_cat2_rating %>
								<input name="starCat2" type="radio" class="star" checked="checked" value="<%= i %>"/>
							<% else %>
								<input name="starCat2" type="radio" class="star" value="<%= i %>"/>
							<% end %>
						<% end %>
						<br>
						<textarea cols="30" rows="3" name="Cat2Comment"><%= @rating.Cat2comment %></textarea>
						<br>
						<%= f.submit "Update" %>
					<% end %>
				<% else %>
		  		<!-- user has NOT rated this location -->
				 	<%= form_for :rating, :url => new_rating_path(:location_id => @location.id) do |f| %>
				    <b>Your Cat1 rating:</b><br>
						<% (1..5).each do |i| %>
							<% if i == current_user_cat1_rating %>
								<input name="starCat1" type="radio" class="star" checked="checked" value="<%= i %>"/>
							<% else %>
								<input name="starCat1" type="radio" class="star" value="<%= i %>"/>
							<% end %>
						<% end %>
						<br>
						<textarea cols="30" rows="3" name="Cat1Comment"></textarea>
						<br>
				    <b>Your Cat2 rating:</b><br>
						<% (1..5).each do |i| %>
							<% if i == current_user_cat2_rating %>
								<input name="starCat2" type="radio" class="star" checked="checked" value="<%= i %>"/>
							<% else %>
								<input name="starCat2" type="radio" class="star" value="<%= i %>"/>
							<% end %>
						<% end %>
						<br>
						<textarea cols="30" rows="3" name="Cat2Comment"></textarea>
						<br>
						<%= f.submit "Update" %>		  
					<% end %>
				<% end %>
    <% else %>
			<!-- user not logged in -->
			If you login you can rate this location!				
    <% end %>
  </p>

  <p>
    <b>Avg Cat1 rating:</b>
    <%= @location.average_cat1_rating %>
  </p>

  <p>
    <b>Avg Cat2 rating:</b>
    <%= @location.average_cat2_rating %>
  </p>

  <p>
    <b>Lat:</b>
    <span id="location_lat"><%= @location.lat %></span>
  </p>

  <p>
    <b>Lng:</b>
    <span id="location_lng"><%= @location.lng %></span>
  </p>

	
</div>